name: stack

on:
  push:
    paths:
      - '.github/workflows/stack.yml'
      - 'stack/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Configure Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/hachisecurity/plutus-stack
          tags: |
            type=edge,enable=true,priority=700,prefix=,suffix=,branch=$repo.default_branch
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Authenticate to package registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and publish plutus-stack image
        uses: docker/build-push-action@v4
        with:
          context: stack
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
